
{REDUND_ERROR} {REDUND_UNREPLICABLE} FUNCTION_BLOCK PWM (*TODO: Add your comment here*) (*$GROUP=User,$CAT=User,$GROUPICON=User.png,$CATICON=User.png*)
	VAR_INPUT
		duty_cycle : {REDUND_UNREPLICABLE} REAL;
		period : {REDUND_UNREPLICABLE} TIME;
	END_VAR
END_FUNCTION_BLOCK
