@echo off
:: Autogenerated script file
SETLOCAL EnableDelayedExpansion
set SOURCE=.\SIM
call :_waitforpid_ %1
:: force remove all files in root directory except script file
for %%f in (*) do (if /i "%%~nxf" neq "%~nx0" del /q /f "%%f")
:: force move all files recursively from 'SOURCE'-folder to root directory
call :_xmove_ %SOURCE% "."
:: restart
start ar000loader.exe
:: remove script file again
del /q %~fx0
:: exit on done
exit /b
:_xmove_
 for /d /r "%1" %%i in (*) do if exist ".\%%~ni" (
 dir "%%i" | find "0 File(s)" >nul & if errorlevel 1 move /y "%%i\*.*" "%2\%%~ni") else (
 move /y "%%i" "%2")
 move /y "%1\*" "%2"
 rd /s /q "%1"
goto :eof
:_waitforpid_
 tasklist /fi "pid eq %1" 2>nul | find "%1" >nul
 if %errorlevel%==0 (
   timeout /t 2 /nobreak >nul
   goto :_waitforpid_
 )
goto :eof
